stages:
  - build
  - pages

build:
  image: debian
  stage: build
  interruptible: true
  script:
    - apt update && apt install -y --no-install-recommends ca-certificates python3 wget && wget "https://github.com/tetrane/dependencies_installer/raw/master/installer.py" && chmod +x installer.py
    - ./installer.py $(find . -wholename "*dependencies/dev")
    - MDBOOK_PREPROCESSOR__TERA__COMMAND="mdbook-tera --toml ./contexts/standalone.toml" mdbook build
    - cp -r static/ book/
  artifacts:
    paths:
      - book

pages:
  stage: pages
  script:
    - cp -r book public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
