[book]
authors = ["Louis Dureuil"]
language = "en"
multilingual = false
src = "src"
title = "Reven API Cookbook"

[output.html]
additional-css = ["bulma.css"]

[preprocessor.tera]
command = "mdbook-tera --toml ./contexts/standalone.toml"
